version: '3'

services:

  web:
    build: ./web
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - ${APP_IPPORT_HOST}:${APP_PORT_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}

  db:
    build: ./db
    #для версии 8.0 и выше добавляем директиву:
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${APP_IPPORT_ADMINER_HOST}:${APP_PORT_ADMINER_CONTAINER}