version: '3'

services:

  php:
    build: ./php
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - ${APP_IPPORT_HOST}:${APP_PORT_CONTAINER}
      #Если нужно прокинуть сайт в интернет, расскоментируй эту строку укажи верный IP-адрес в .env
      #- ${APP_IPPORT_HOST_WEB}:${APP_PORT_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}

  mysql:
    build: ./mysql
    #для версии 8.0 и выше добавляем директиву:
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${APP_IPPORT_ADMINER_HOST}:${APP_PORT_ADMINER_CONTAINER}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${APP_IPPORT_PHPMYADMIN_HOST}:${APP_PORT_PHPMYADMIN_CONTAINER}
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_ROOT_PASSWORD}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}